### ISSUE TITLE
Allow color of active facet to be set with a css parameter

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#3174]
https://github.com/projectblacklight/blacklight/blob/7d228b1316bc86b33c1cdb46f4eed9d1a7b46861/app/assets/stylesheets/blacklight/_facets.scss#L117-L124

```css
.facet-limit-active .card-header .btn {
  color: #fff;
}
```

This allows adopters to not need to compile sass.
