### ISSUE TITLE
Make application name easier to change.

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#558]
concerning this method:  https://github.com/projectblacklight/blacklight/blob/master/app/helpers/blacklight/blacklight_helper_behavior.rb#L13-L17

What if our generator injected this into config/locales/en.yml:

``` yaml
en:
  blacklight:
    application_name: "Blacklight"
```

I'm thinking this would make it easer to find "How do I change this from the default"?
