### ISSUE TITLE
Stacked navbar prevents dropdowns in top navbar

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#719]
![screen shot 2014-01-29 at 2 37 45 pm](https://f.cloud.github.com/assets/92044/2034046/4b2858a0-8925-11e3-97f8-d0cd0d9de919.png)

.navbar has position: relative which causes it to go over the dropdown.

I recommend we remove the `navbar` class from the search bar and add these styles:

``` css
#search-navbar {
  margin-right: 0;
  margin-left: 0;
  margin-top: -20px;
  border: 1px solid #e7e7e7;
}
```
